sudo: false
language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - python setup.py nosetests -a !system,!manual,!event_test,!load
